language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - "pip install -e ."
  - pip install coverage==4.5.4
script:
  - pytest
  - "coverage run --source=orographic_precipitation setup.py test"

after_success:
  - coveralls
