name: test build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Run pytest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          mamba-version: "*"
          channels: conda-forge,defaults
          channel-priority: true
          activate-environment: orographic-precipitation
          environment-file: environment.yml
      - name: Conda info
        shell: bash -l {0}
        run: conda info
      - name: Conda list
        shell: bash -l {0}
        run: conda list
      - name: Install orographic-precipitation
        shell: bash -l {0}
        run: |
          pip install --no-deps -e .
          python -OO -c "import orographic_precipitation"
      - name: Run tests
        shell: bash -l {0}
        run: pytest orographic-precipitation --cov=orographic-precipitation --cov-report term-missing --cov-report xml --verbose --color=yes
        continue-on-error: ${{ matrix.cfg.allow-failure }}
      - name: Codecov
        if: matrix.cfg.codecov
        uses: codecov/codecov-action@v1
